name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Tarpaulin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin --version 0.25.2

      - name: Run code coverage check with tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --workspace --timeout 120
